apiVersion: v1
kind: PersistentVolume
metadata:
  name: openfga-postgresql-pv
  labels:
    type: local
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/postgresql"
