---
apiVersion: kueue.x-k8s.io/v1beta2
kind: WorkloadPriorityClass
metadata:
  name: low-priority-training
value: 25
description: "Low priority workloads for training jobs"
---
apiVersion: kueue.x-k8s.io/v1beta2
kind: WorkloadPriorityClass
metadata:
  name: standard-priority-training
value: 50
description: "Standard/medium priority workloads for training jobs"
---
apiVersion: kueue.x-k8s.io/v1beta2
kind: WorkloadPriorityClass
metadata:
  name: high-priority-training
value: 100
description: "High priority workloads for training jobs"

